Hw03 frequency analysis
desperatenix/go_study pull request #3
Opened 2021-04-15 18:04 UTC by desperatenix

2021-04-17 13:41 UTC, agneum requested changes
Спасибо за выполненное задание. Отличная работа, но не хватает дополнительных тестов.
Итого: 6 баллов из 10

Просьба при создании PR использовать шаблон(детали в инструкции по сдаче ДЗ)

2021-04-17 13:41 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	var wc []kv //nolint
С точки зрения оптимальности лучше сразу задать capacity слайсу, чтобы не производить лишние аллокации при append. Capacity слайса равна размеру мапы

2021-04-17 13:41 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	})
Оптимальнее сортировать за один вызов sort.Slice. Внутри функции можно делать более сложные проверки, то есть проверить и по алфавиту, и счётчик

2021-04-17 13:41 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	var wordsSlice []kv
В качестве значения по умолчанию можно выбрать переменную `wc`, тогда в условии ниже можно обойтись без `else`

2021-04-20 13:32 UTC, desperatenix commented on hw03_frequency_analysis/top.go
> +	})
Поправил

2021-04-20 13:33 UTC, desperatenix commented on hw03_frequency_analysis/top.go
> +	var wc []kv //nolint
исправлено

2021-04-21 02:08 UTC, agneum approved these changes
Спасибо за изменения
Статус: принято
Итого: 10 баллов из 10

2021-04-21 14:43 UTC, merged